name: Terraform Multi-Env Pipeline

on:
  workflow_dispatch:

jobs:

  dev:
    uses: ./.github/workflows/terraform.yml
    with:
      env: dev
    secrets: inherit

  staging:
    needs: dev
    uses: ./.github/workflows/terraform.yml
    with:
      env: staging
    secrets: inherit

  prod:
    needs: staging
    uses: ./.github/workflows/terraform.yml
    with:
      env: prod
    secrets: inherit
